language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
sudo: required

install:
- dotnet restore

script:
 - dotnet build -c Release

deploy:
  provider: script
  skip_cleanup: true
  script:
  - cd Discord.Net.CustomCommands/bin/Release && dotnet nuget push *.nupkg --source $NUGET_FEEDURL
  on:
    branch: master